seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#222222'
  medium-text_color: '#444444'
  light-text_color: '#f7f5f3'
  featured-text_color: '#d8a5a5'
  dark_color: '#E6BFA9'
  medium_color: '#EFDADA'
  light_color: '#F7EBE4'
  v-light_color: '#FBF6F3'
  featured_color: '#EDE7DD'
  featured-light_color: '#F7F2EC'
  accent_color: '#F5BBA3'
